### ISSUE TITLE
[TLS] 

### ISSUE THREAD

**Issue by kaiserboss** [blue-yonder/bonfire#14]
Hello

Can you tell me how to use tls with bonfire?

When I try to connect to graylog with tls options, it tells me that message:

[SSL: CERTIFICATE_VERIFY_FAILED]

Any clue? Thank you!

Ragards.

**Comment by valentin-krasontovitsch** [comment]
closing as perhaps problem with self-signed certificate or similar, and presumably not relevant anymore. 

feel free to reopen if this becomse relevant again.
