### ISSUE TITLE
six required version == 1.9.0?

### ISSUE THREAD

**Issue by emillynge** [blue-yonder/bonfire#20]
Hi, why is six version pinned to 1.9.0 ?

This makes bonfire raise this error after another package has upgraded the six package:
`pkg_resources.DistributionNotFound: The 'six==1.9.0' distribution was not found and is required by bonfire`

Could it possibly be changed to require six>=1.9.0 ?

**Comment by valentin-krasontovitsch** [comment]
fixed in 09cebae634e119e7fb88fd416fa8bac765575ffe, just needs to be released (cf. #26)

**Comment by valentin-krasontovitsch** [comment]
released in 0.0.8 today
