### ISSUE TITLE
latest version in pip 0.0.7 does not include endpoint support

### ISSUE THREAD

**Issue by dlamblin** [blue-yonder/bonfire#26]
Do you plan to release a version supporting the api endpoint?

**Comment by valentin-krasontovitsch** [comment]
let's do this. ... how does one do this? : D

any pointers on technical things that have to be done besides tagging a commit and pushing said tag to github will be greatly appreciated! ... I'm unfortunately not familiar with publishing pip packages.

**Comment by relvacode** [comment]
Any update on this? You can use [twine](https://pypi.org/project/twine/) to push packages to PyPI

**Comment by valentin-krasontovitsch** [comment]
on vacation next week - unless I get to look at it this weekend, it'll have to wait a bit longer.

thanks for the pointer though - gonna check out twine.

**Comment by valentin-krasontovitsch** [comment]
ok ok ok super duper late, I know, shame, but i'm finally doing it! except of course i need to have authorization for pushing to pypi - @mahrz24 would you mind adding me? I created an account with the username `v.krasontov` on pypi.org

**Comment by valentin-krasontovitsch** [comment]
Malte bitte ich brauchen das Rechte fuer die PIP ; )
ping @mahrz24

**Comment by mahrz24** [comment]
Done, sorry for the delay!

**Comment by valentin-krasontovitsch** [comment]
Thanks, Malte!

To anybody still following here - I’m gonna try to push tomorrow.

**Comment by valentin-krasontovitsch** [comment]
fixed by ec7d5306cb2b6c1c7536d266a3cc15cce5b90726, included in v0.0.8 release pushed today.
