### ISSUE TITLE
[RESOLVED] error when using api with windows

### ISSUE THREAD

**Issue by kaiserboss** [blue-yonder/bonfire#7]
Hello,

I have installed bonfire on windows with:

setup.py bdist_wininst

Then I installed with the generated installer.

When i launch bonfire, it told me that it couldn't import syslog.

I commented syslog in graylog_api and formats

Then I have the following error:   

output.py", line 36, in run_logprint
    formatted_msgs = map(reverse, result.messages)
NameError: name 'reverse' is not defined

Could you tell me how to install bonfire on windows?

Regards

**Comment by mahrz** [comment]
Bonfire has not been tested on windows and I don't have access to a windows machine - the syslog package is only needed for the logging level definitions, so in theory it could be exchanged by something platform independent. 

Line 36 of output.py looks different in the repository:

```
formatted_msgs = map(formatter, result.messages)
formatted_msgs.reverse()
```

Did you change anything in else?

**Comment by kaiserboss** [comment]
Hello ,

thank you for your reply.

I have suppressed all syslog import and I have replaced

formatted_msgs = map(formatter, result.messages) 

with 

formatted_msgs = list(map(formatter, result.messages))

Now it works.

Regards.
