### ISSUE TITLE
dump format, no timestamp available.

### ISSUE THREAD

**Issue by csawyerYumaed** [blue-yonder/bonfire#9]
There doesn't seem to be a way to get datetime or timestamp when in dump format (-d).

**Comment by mahrz** [comment]
Sorry for the long silence - I finally came around to fix this issue, the timestamp is now the first column in the format.

**Comment by csawyerYumaed** [comment]
When I saw this in my email, I was like wait, what is Bonfire? why do I care?!  Turns out I really *DO* care, and now I can get a user off of my back! thanks!
